import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Kaushan_Script } from "next/font/google";
import "./globals.css";

const kaushan_script = Kaushan_Script({
   subsets: ["latin"],
   weight: ["400"],
});

const inter = Inter({
   subsets: ["latin"],
   weight: ["400", "500", "600"],
});

export const metadata: Metadata = {
   title: "Comfy store",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en">
         <body
            className={`${inter.className} ${kaushan_script.className}`}
         >
            {children}
         </body>
      </html>
   );
}
